Remove duplicates in Search Api fields
cloudinary/cloudinary_java pull request #227
Opened 2020-11-19 10:06 UTC by francistagbo

Remove duplicates in Search Api fields:
- aggregate
- withField
- sortBy

2020-11-22 11:24 UTC, nitzanj requested changes
The code looks good but without the appropriate test cases we can't be sure it works
Please add tests that specify duplicate fields and see that the query is cleaning those out.

2022-03-17 06:12 UTC, const-cloudinary requested changes
Where is the check for duplicates?

2022-03-17 07:29 UTC, francistagbo commented
Hi @const-cloudinary,

It is in the first commit, the Search.java class

2022-03-17 07:49 UTC, adimiz1 commented
Hi @francistagbo 
@const-cloudinary meant where are the duplicate checks in the tests added to this push
I just added them.

2022-03-17 09:36 UTC, francistagbo commented
Okay, cool! Please let me know if you need anything from my side :)

2022-03-23 14:42 UTC, const-cloudinary requested changes

2022-03-23 14:42 UTC, const-cloudinary commented on cloudinary-core/src/main/java/com/cloudinary/Search.java
> +    public ArrayList<String> getAggregateParam() {
Do you need these public getters?

2022-03-23 14:46 UTC, adimiz1 commented on cloudinary-core/src/main/java/com/cloudinary/Search.java
> +    public ArrayList<String> getAggregateParam() {
Removed

2022-03-23 14:58 UTC, const-cloudinary commented on cloudinary-core/src/main/java/com/cloudinary/Search.java
> +        if (!aggregateParam.contains(field)) {
never mind, java 6

2022-03-23 20:08 UTC, const-cloudinary approved these changes

2022-03-23 21:04 UTC, merged