updated expected text that returns from the server
cloudinary/cloudinary_java pull request #238
Opened 2021-05-03 11:38 UTC by asisayag2

CI test is failing due to change in the text that is returned from the server. 
This change updates the expected value

2021-05-03 12:36 UTC, const-cloudinary approved these changes

2021-05-03 12:40 UTC, patrick-tolosa approved these changes

2021-05-11 17:26 UTC, patrick-tolosa approved these changes

2021-05-12 10:05 UTC, const-cloudinary requested changes

2021-05-12 10:05 UTC, const-cloudinary commented on cloudinary-core/src/test/java/com/cloudinary/transformation/LayerTest.java
> +                new Layer().publicId("logo__111"), //testing SNI-4729
Please avoid mentioning internal tickets.

2021-05-12 13:46 UTC, const-cloudinary requested changes

2021-05-12 13:46 UTC, const-cloudinary commented on cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractAccountApiTest.java
> +        deleteUser(id);
Please move all `deleteUser` calls to `tearDown`, if assertion fails, this line is never called.

2021-05-25 06:40 UTC, merged