Fix double underscore handling during normalization.
cloudinary/cloudinary_java pull request #255
Opened 2022-03-11 15:00 UTC by YomesInc

2022-03-13 07:43 UTC, adimiz1 approved these changes

2022-03-14 09:53 UTC, const-cloudinary requested changes
@YomesInc, please add tests that verify that expressions are indeed normalized. You might break the normalization functionality here.

2022-03-24 02:01 UTC, YomesInc commented
> @YomesInc, please add tests that verify that expressions are indeed normalized. You might break the normalization functionality here.

@const-cloudinary are tests in https://github.com/cloudinary/cloudinary_java/pull/262 enough? If not, we need test cases from them (expressions that should be tested).

2022-04-09 20:24 UTC, const-cloudinary approved these changes

2022-04-10 05:31 UTC, adimiz1 approved these changes

2022-04-10 05:32 UTC, merged