Support multiple acls in cookies
cloudinary/cloudinary_java pull request #259
Opened 2022-03-17 22:31 UTC by YomesInc

2022-03-21 05:57 UTC, adimiz1 commented on cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
> +        } else if (field.get(instance) instanceof List) {
@YomesInc can you please explain this change, I was not sure what it's related to

2022-03-21 05:57 UTC, adimiz1 requested changes

2022-03-21 05:57 UTC, adimiz1 commented on cloudinary-core/src/test/java/com/cloudinary/test/CloudinaryTest.java
> +            field.set(instance, Collections.singletonList(cloudinary.randomPublicId()));
@YomesInc can you please explain this change, I was not sure what it's related to

2022-03-27 08:44 UTC, adimiz1 approved these changes

2022-03-30 09:25 UTC, const-cloudinary approved these changes

2022-03-30 13:39 UTC, merged