Fix transformations API call
cloudinary/cloudinary_java pull request #271
Opened 2022-03-21 21:35 UTC by YomesInc

2022-03-22 14:24 UTC, const-cloudinary requested changes

2022-03-28 11:26 UTC, adimiz1 approved these changes

2022-04-03 04:55 UTC, adimiz1 approved these changes

2022-04-04 09:23 UTC, const-cloudinary approved these changes

2022-04-04 09:28 UTC, patrick-tolosa commented
@YomesInc @adimiz1 please add a description in this PR,
We should not have empty PRs.

2022-04-04 09:53 UTC, merged