Get resources by asset folder
cloudinary/cloudinary_java pull request #282
Opened 2022-09-04 08:08 UTC by adimiz1

### Brief Summary of Changes
Add new API call , get resources by asset folder

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [x] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Reviewer, please note:

#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2022-09-04 11:42 UTC, const-cloudinary requested changes

2022-09-04 11:42 UTC, const-cloudinary commented on cloudinary-core/src/main/java/com/cloudinary/Api.java
> +    public ApiResponse resourceByAssetFolder(String assetFolder, Map options) throws Exception {
```suggestion
    public ApiResponse resourcesByAssetFolder(String assetFolder, Map options) throws Exception {
```

2022-09-04 11:44 UTC, const-cloudinary commented on cloudinary-core/src/main/java/com/cloudinary/Api.java
> +        Map params = ObjectUtils.only(options, "tags", "context", "moderations");
it also looks like need to add next_cursor and max_results parameters

2022-09-04 16:56 UTC, const-cloudinary approved these changes

2022-09-05 04:49 UTC, strausr approved these changes

2022-09-07 05:10 UTC, strausr approved these changes

2022-09-08 04:07 UTC, merged