Add derived next cursor support
cloudinary/cloudinary_java pull request #330
Opened 2024-08-14 09:53 UTC by adimiz1

### Brief Summary of Changes
Add derived next cursor support

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [x] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Reviewer, please note:

#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

2024-08-15 08:11 UTC, const-cloudinary requested changes

2024-08-15 08:11 UTC, const-cloudinary commented on cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
> +        cloudinary.uploader().upload(SRC_TEST_IMAGE, options);
Where do you delete these assets?

2024-08-15 08:25 UTC, adimiz1 commented on cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
> +        cloudinary.uploader().upload(SRC_TEST_IMAGE, options);
Done

2024-08-18 08:44 UTC, const-cloudinary requested changes

2024-08-18 08:44 UTC, const-cloudinary commented on cloudinary-test-common/src/main/java/com/cloudinary/test/AbstractApiTest.java
> +        cloudinary.uploader().destroy(publicId, Collections.singletonMap("invalidate", true));
If one of your assertions fails, this line is never called.

2024-08-19 08:44 UTC, const-cloudinary approved these changes

2024-08-19 09:13 UTC, merged